// PhET HTML5 catalog with curated primarySubject for browse filters
var PHET_SUBJECTS = [
    { id: 'all', label: 'All' },
    { id: 'biology', label: 'Biology' },
    { id: 'chemistry', label: 'Chemistry' },
    { id: 'physics', label: 'Physics' },
    { id: 'math', label: 'Math' },
    { id: 'earth', label: 'Earth & Space' }
];
var PHET_SIM_CATALOG = {
    'acid-base-solutions': { label: 'Acid-Base Solutions', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, acid, base, solutions', blurb: 'Acid-Base Solutions' },
    'area-model-algebra': { label: 'Area Model Algebra', primarySubject: 'math', subjects: 'math', topics: 'math, area, model, algebra', blurb: 'Area Model Algebra' },
    'area-model-multiplication': { label: 'Area Model Multiplication', primarySubject: 'math', subjects: 'math', topics: 'math, area, model, multiplication', blurb: 'Area Model Multiplication' },
    'balancing-chemical-equations': { label: 'Balancing Chemical Equations', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, balancing, chemical, equations', blurb: 'Balancing Chemical Equations' },
    'balloons-and-static-electricity': { label: 'Balloons and Static Electricity', primarySubject: 'physics', subjects: 'physics,electricity,chemistry,biology,general', topics: 'physics, electricity, chemistry, biology, general, balloons, and, static', blurb: 'Balloons and Static Electricity' },
    'beers-law-lab': { label: 'Beer\'s Law Lab', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, beer\'s, law, lab, beers', blurb: 'Beer\'s Law Lab' },
    'bending-light': { label: 'Bending Light', primarySubject: 'earth', subjects: 'physics,astronomy', topics: 'physics, astronomy, bending, light', blurb: 'Bending Light' },
    'blackbody-spectrum': { label: 'Blackbody Spectrum', primarySubject: 'earth', subjects: 'physics,earth,astronomy,chemistry,biology,quantum', topics: 'physics, earth, astronomy, chemistry, biology, quantum, blackbody, spectrum', blurb: 'Blackbody Spectrum' },
    'build-a-molecule': { label: 'Build a Molecule', primarySubject: 'chemistry', subjects: 'chemistry,general,biology', topics: 'chemistry, general, biology, build, molecule, a, bond, Lewis, chemical', blurb: 'Build a Molecule' },
    'build-a-nucleus': { label: 'Build a Nucleus', primarySubject: 'chemistry', subjects: 'physics,chemistry', topics: 'physics, chemistry, build, nucleus, a', blurb: 'Build a Nucleus' },
    'build-an-atom': { label: 'Build an Atom', primarySubject: 'chemistry', subjects: 'physics,chemistry,general,biology', topics: 'physics, chemistry, general, biology, build, atom, an, proton, neutron, electron, element, periodic', blurb: 'Build an Atom' },
    'buoyancy-basics': { label: 'Buoyancy: Basics', primarySubject: 'physics', subjects: 'physics,math', topics: 'physics, math, buoyancy, basics', blurb: 'Buoyancy: Basics' },
    'capacitor-lab-basics': { label: 'Capacitor Lab: Basics', primarySubject: 'physics', subjects: 'physics,electricity', topics: 'physics, electricity, capacitor, lab, basics', blurb: 'Capacitor Lab: Basics' },
    'charges-and-fields': { label: 'Charges and Fields', primarySubject: 'physics', subjects: 'physics,electricity', topics: 'physics, electricity, charges, and, fields', blurb: 'Charges and Fields' },
    'circuit-construction-kit-ac': { label: 'Circuit Construction Kit: AC', primarySubject: 'physics', subjects: 'physics,electricity', topics: 'physics, electricity, circuit, construction, kit, ac', blurb: 'Circuit Construction Kit: AC' },
    'circuit-construction-kit-dc': { label: 'Circuit Construction Kit: DC', primarySubject: 'physics', subjects: 'physics,electricity', topics: 'physics, electricity, circuit, construction, kit, dc', blurb: 'Circuit Construction Kit: DC' },
    'color-vision': { label: 'Color Vision', primarySubject: 'biology', subjects: 'physics,astronomy,biology', topics: 'physics, astronomy, biology, color, vision, eye, light, filter, rgb, perception', blurb: 'Color Vision' },
    'concentration': { label: 'Concentration', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, concentration', blurb: 'Concentration' },
    'coulombs-law': { label: 'Coulomb\'s Law', primarySubject: 'physics', subjects: 'physics,electricity,chemistry,general', topics: 'physics, electricity, chemistry, general, coulomb\'s, law, coulombs', blurb: 'Coulomb\'s Law' },
    'density': { label: 'Density', primarySubject: 'biology', subjects: 'physics,chemistry,biology,general', topics: 'physics, chemistry, biology, general, density, mass, volume, float, sink, matter', blurb: 'Density' },
    'diffusion': { label: 'Diffusion', primarySubject: 'biology', subjects: 'physics,chemistry,biology,general', topics: 'physics, chemistry, biology, general, diffusion, concentration, gradient, particle, cell, membrane', blurb: 'Diffusion' },
    'energy-skate-park-basics': { label: 'Energy Skate Park: Basics', primarySubject: 'physics', subjects: 'physics,math', topics: 'physics, math, energy, skate, park, basics', blurb: 'Energy Skate Park: Basics' },
    'equality-explorer': { label: 'Equality Explorer', primarySubject: 'math', subjects: 'math', topics: 'math, equality, explorer', blurb: 'Equality Explorer' },
    'expression-exchange': { label: 'Expression Exchange', primarySubject: 'math', subjects: 'math', topics: 'math, expression, exchange', blurb: 'Expression Exchange' },
    'faradays-law': { label: 'Faraday\'s Law', primarySubject: 'physics', subjects: 'physics,electricity', topics: 'physics, electricity, faraday\'s, law, faradays', blurb: 'Faraday\'s Law' },
    'forces-and-motion-basics': { label: 'Forces and Motion: Basics', primarySubject: 'physics', subjects: 'physics,math', topics: 'physics, math, forces, and, motion, basics, newton, newtons, law, laws, inertia, acceleration, mechanics, friction, push, pull', blurb: 'Forces and Motion: Basics' },
    'fractions-equality': { label: 'Fractions: Equality', primarySubject: 'math', subjects: 'math', topics: 'math, fractions, equality', blurb: 'Fractions: Equality' },
    'fractions-intro': { label: 'Fractions: Intro', primarySubject: 'math', subjects: 'math', topics: 'math, fractions, intro', blurb: 'Fractions: Intro' },
    'friction': { label: 'Friction', primarySubject: 'physics', subjects: 'physics,math', topics: 'physics, math, friction', blurb: 'Friction' },
    'function-builder': { label: 'Function Builder', primarySubject: 'math', subjects: 'math', topics: 'math, function, builder', blurb: 'Function Builder' },
    'gas-properties': { label: 'Gas Properties', primarySubject: 'chemistry', subjects: 'physics,chemistry,biology,general', topics: 'physics, chemistry, biology, general, gas, properties', blurb: 'Gas Properties' },
    'gases-intro': { label: 'Gases Intro', primarySubject: 'chemistry', subjects: 'physics,chemistry,biology,general', topics: 'physics, chemistry, biology, general, gases, intro, gas, pressure, temperature, particle', blurb: 'Gases Intro' },
    'gene-expression-essentials': { label: 'Gene Expression Essentials', primarySubject: 'biology', subjects: 'biology', topics: 'biology, gene, expression, essentials, transcription, translation, DNA, RNA, protein, cell', blurb: 'Gene Expression Essentials' },
    'graphing-lines': { label: 'Graphing Lines', primarySubject: 'math', subjects: 'math', topics: 'math, graphing, lines', blurb: 'Graphing Lines' },
    'graphing-quadratics': { label: 'Graphing Quadratics', primarySubject: 'math', subjects: 'math', topics: 'math, graphing, quadratics', blurb: 'Graphing Quadratics' },
    'graphing-slope-intercept': { label: 'Graphing Slope-Intercept', primarySubject: 'math', subjects: 'math', topics: 'math, graphing, slope, intercept', blurb: 'Graphing Slope-Intercept' },
    'gravity-and-orbits': { label: 'Gravity and Orbits', primarySubject: 'earth', subjects: 'physics,math,biology', topics: 'physics, math, biology, gravity, and, orbits', blurb: 'Gravity and Orbits' },
    'gravity-force-lab-basics': { label: 'Gravity Force Lab: Basics', primarySubject: 'physics', subjects: 'physics,math,biology', topics: 'physics, math, biology, gravity, force, lab, basics', blurb: 'Gravity Force Lab: Basics' },
    'greenhouse-effect': { label: 'Greenhouse Effect', primarySubject: 'biology', subjects: 'biology', topics: 'biology, greenhouse, effect', blurb: 'Greenhouse Effect' },
    'isotopes-and-atomic-mass': { label: 'Isotopes and Atomic Mass', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, isotopes, and, atomic, mass', blurb: 'Isotopes and Atomic Mass' },
    'john-travoltage': { label: 'John Travoltage', primarySubject: 'physics', subjects: 'physics,electricity', topics: 'physics, electricity, john, travoltage', blurb: 'John Travoltage' },
    'keplers-laws': { label: 'Kepler\'s Laws', primarySubject: 'earth', subjects: 'physics,math,biology,engineering', topics: 'physics, math, biology, engineering, kepler\'s, laws, keplers', blurb: 'Kepler\'s Laws' },
    'lasers': { label: 'Lasers', primarySubject: 'earth', subjects: 'physics,earth,astronomy,chemistry,quantum', topics: 'physics, earth, astronomy, chemistry, quantum, lasers', blurb: 'Lasers' },
    'membrane-transport': { label: 'Membrane Transport', primarySubject: 'biology', subjects: 'chemistry,general,biology', topics: 'chemistry, general, biology, membrane, transport, channel, ion, osmosis, cell, diffusion', blurb: 'Membrane Transport' },
    'models-of-the-hydrogen-atom': { label: 'Models of the Hydrogen Atom', primarySubject: 'physics', subjects: 'physics,earth,astronomy,chemistry,general,quantum', topics: 'physics, earth, astronomy, chemistry, general, quantum, models, the, hydrogen, atom, of', blurb: 'Models of the Hydrogen Atom' },
    'molarity': { label: 'Molarity', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, molarity', blurb: 'Molarity' },
    'molecule-polarity': { label: 'Molecule Polarity', primarySubject: 'chemistry', subjects: 'chemistry,general,biology', topics: 'chemistry, general, biology, molecule, polarity, bond, electronegativity, dipole, water', blurb: 'Molecule Polarity' },
    'molecule-shapes': { label: 'Molecule Shapes', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, molecule, shapes', blurb: 'Molecule Shapes' },
    'molecules-and-light': { label: 'Molecules and Light', primarySubject: 'earth', subjects: 'physics,astronomy,chemistry,biology,general', topics: 'physics, astronomy, chemistry, biology, general, molecules, and, light', blurb: 'Molecules and Light' },
    'my-solar-system': { label: 'My Solar System', primarySubject: 'earth', subjects: 'physics,math,biology', topics: 'physics, math, biology, solar, system, my', blurb: 'My Solar System' },
    'natural-selection': { label: 'Natural Selection', primarySubject: 'biology', subjects: 'biology', topics: 'biology, natural, selection, evolution, allele, bunny, population, genetics, darwin', blurb: 'Natural Selection' },
    'neuron': { label: 'Neuron', primarySubject: 'biology', subjects: 'biology', topics: 'biology, neuron, nerve, stimulus, action potential, brain, nervous system', blurb: 'Neuron' },
    'number-compare': { label: 'Number Compare', primarySubject: 'math', subjects: 'math', topics: 'math, number, compare', blurb: 'Number Compare' },
    'number-play': { label: 'Number Play', primarySubject: 'math', subjects: 'math', topics: 'math, number, play', blurb: 'Number Play' },
    'pendulum-lab': { label: 'Pendulum Lab', primarySubject: 'physics', subjects: 'physics,math,engineering', topics: 'physics, math, engineering, pendulum, lab', blurb: 'Pendulum Lab' },
    'ph-scale': { label: 'pH Scale', primarySubject: 'chemistry', subjects: 'chemistry,biology,general', topics: 'chemistry, biology, general, scale, ph, acid, base, alkaline, neutral, solution', blurb: 'pH Scale' },
    'ph-scale-basics': { label: 'pH Scale: Basics', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, scale, basics, ph', blurb: 'pH Scale: Basics' },
    'photoelectric': { label: 'Photoelectric Effect', primarySubject: 'earth', subjects: 'physics,earth,astronomy,chemistry,general,quantum', topics: 'physics, earth, astronomy, chemistry, general, quantum, photoelectric, effect', blurb: 'Photoelectric Effect' },
    'plinko-probability': { label: 'Plinko Probability', primarySubject: 'math', subjects: 'math', topics: 'math, plinko, probability', blurb: 'Plinko Probability' },
    'projectile-motion': { label: 'Projectile Motion', primarySubject: 'physics', subjects: 'physics,math,engineering', topics: 'physics, math, engineering, projectile, motion', blurb: 'Projectile Motion' },
    'quantum-coin-toss': { label: 'Quantum Coin Toss', primarySubject: 'physics', subjects: 'physics,chemistry,quantum', topics: 'physics, chemistry, quantum, coin, toss', blurb: 'Quantum Coin Toss' },
    'ratio-and-proportion': { label: 'Ratio and Proportion', primarySubject: 'math', subjects: 'math', topics: 'math, ratio, and, proportion', blurb: 'Ratio and Proportion' },
    'reactants-products-and-leftovers': { label: 'Reactants, Products and Leftovers', primarySubject: 'chemistry', subjects: 'chemistry,general', topics: 'chemistry, general, reactants,, products, and, leftovers, reactants', blurb: 'Reactants, Products and Leftovers' },
    'rutherford-scattering': { label: 'Rutherford Scattering', primarySubject: 'physics', subjects: 'physics,earth,chemistry,general', topics: 'physics, earth, chemistry, general, rutherford, scattering', blurb: 'Rutherford Scattering' },
    'sound': { label: 'Sound', primarySubject: 'physics', subjects: 'physics,biology', topics: 'physics, biology, sound', blurb: 'Sound' },
    'spinning-charge': { label: 'spinning charge', primarySubject: 'physics', subjects: '', topics: 'spinning, charge', blurb: 'spinning charge' },
    'states-of-matter': { label: 'States of Matter', primarySubject: 'chemistry', subjects: 'physics,chemistry,general', topics: 'physics, chemistry, general, states, matter, of', blurb: 'States of Matter' },
    'states-of-matter-basics': { label: 'States of Matter: Basics', primarySubject: 'chemistry', subjects: 'physics,chemistry,general', topics: 'physics, chemistry, general, states, matter, basics, of', blurb: 'States of Matter: Basics' },
    'under-pressure': { label: 'Under Pressure', primarySubject: 'physics', subjects: 'physics,biology', topics: 'physics, biology, under, pressure', blurb: 'Under Pressure' },
    'wave-interference': { label: 'Wave Interference', primarySubject: 'earth', subjects: 'physics,astronomy,biology', topics: 'physics, astronomy, biology, wave, interference', blurb: 'Wave Interference' },
    'wave-on-a-string': { label: 'Wave on a String', primarySubject: 'earth', subjects: 'physics,chemistry,biology,math,general,engineering', topics: 'physics, chemistry, biology, math, general, engineering, wave, string, on, a', blurb: 'Wave on a String' },
    'waves-intro': { label: 'Waves Intro', primarySubject: 'earth', subjects: 'physics,astronomy,biology', topics: 'physics, astronomy, biology, waves, intro', blurb: 'Waves Intro' },
};
var PHET_SIM_IDS = new Set(Object.keys(PHET_SIM_CATALOG));
var PHET_CATALOG_PROMPT = Object.entries(PHET_SIM_CATALOG).map(([id, meta]) => `- "${id}": ${meta.label} (${meta.topics})`).join("\n");
